//Definiendo variables
var nombre = 'Fernando';

//Imprimir contenido de la variables nombre
console.log(nombre);

//Definiendo datos personales con variables
var nomPersona = 'Gloria';
var apePersona = 'Guerra Paz';
var edadPersona = 20;
var procPersona = 'San vicente';

//Imprimir datos personales
console.log('Mi nombre es ' + nomPersona + ' y mis apellidos son ' + apePersona)
console.log('Mi edad es ' + edadPersona + ' y soy del distrito de ' + procPersona);

//Deniendo variables numéricas y cálculos respectivos
var numUno = 100;
var numDos = 350;
var suma = numUno + numDos;
var resta = numDos - numUno
var producto = numUno + numDos;
var divide = numDos / numUno;
var mayor = numDos > numUno;
var comparar = numUno == numDos;

//Imprimir resultados 
console.log('La suma del ' + numUno + ' más ' + numDos + ' es ' + suma);
console.log('La resta de ' + numDos + ' menos ' + numUno + ' es ' + resta);
console.log('La multiplicación de ' + numUno + ' por ' + numDos + ' es ' + producto);
console.log(' la división ' + numUno + ' entre ' + numUno + ' es ' + divide);
console.log(' La comparación ' + nunUno +  ' es igual o diferente que el ' + numDos + ' es ' + comprar);





//Resolver 
var producto = 'zapatillas nike';
var cantidad = 10;
var precio = 125;
var total  = cantidad * precio;

//Imprimir mensaje de resultado 
console.log('El precio a pagar por el producto') + producto + ' es ' + total);

//Definir array con los dias de la semana
var diasSemana = ['Lunes', 'Martes', 'Miercoles','Jueves', 'Viernes', 'Sabado' , 'Domingo'];

//Imprimiendo el contenido de la variable de tipo array
console.log(diasSemana);
console.log(diasSemana[4]);
console.log(diasSemana[2]);

//crear un array con 5 nombres de personas e Impri
 var gente = ['Juan' , 'pedro' , ' alberto ' , ' jimmy ', 'luis '];
 console.log(gente);
 console.log(genteñ{0});
 console.log(genteñ{1});
 console.log(genteñ{2});
 console.log(genteñ{3});
 console.log(genteñ{4});

